### ISSUE TITLE
F5 - Baseline configuration not applying

### ISSUE THREAD

**Issue by cgtheflash** [mikeoleary/azure-f5-palo#10]
The F5 baseline configuration in the baseline.json file that configures the virtual server in F5 is not being applied though arm does not show any errors for the f5linkedtemplate deployment.

**Comment by cgtheflash** [comment]
ignorance on my part

**Comment by mikeoleary** [comment]
No problem @cgtheflash 
If you want help just shoot me a message. This was intended for customers to see how they can deploy f5 easily but it’s a 2 yr old demo.

**Comment by cgtheflash** [comment]
I would be glad to help out in any way i can. I'll see if I can get the Palo bootstrap working. There aren't many resources out there showing how to handle an active pair of F5's in Azure behind a pair of Palo's. Your baseline.json really helped me understand what i needed to do to forward the traffic back outbound (return traffic). I also like that the solution doesn't require the source nat. Thank you for providing this.

**Comment by mikeoleary** [comment]
@cgtheflash Are you a f5 or PA employee? I don’t recognize the handle. If yes can you reach out internally?

**Comment by cgtheflash** [comment]
I am not. I am just a cloud consultant that stumbled on your work and found it to be quite helpful.

**Comment by mikeoleary** [comment]
@cgtheflash can you shoot me an email ? My email is mi.oleary@f5.com - perhaps we can find something more specific to help your customers. 

I’m not sure if youve read the accompanying article for this demo, but the purpose behind this is to simply set up a demo environment.  
https://devcentral.f5.com/s/articles/Deploy-F5-and-PaloAlto-in-Azure-with-this-demo
